### ISSUE TITLE
Moon bug

### ISSUE THREAD

**Issue by criscky** [Minecraft-Eternal/MC-Eternal-1.12#160]
Old issue from the old git

https://github.com/adam9899/Issues/issues/940

**Comment by embeddedt** [comment]
This is a drive-by comment, so feel free to ignore, but I suspect that [these lines of code](https://github.com/Brian-Wuest/MC-FromTheDepths/blob/3f999f288c0c46fbb816dd9653554037222d7213/src/main/java/com/wuest/from_the_depths/Base/TileEntityBase.java#L137-L144) in the affected mod may be related, especially since the original issue seems to be triggered specifically by chunk unloads. AFAIK it is not necessary to override `onChunkUnload` in order for a tile entity's data to be saved, at least not in 1.12.

**Comment by criscky** [comment]
please report that to the dev
we are trying to fix in our end, but i dont know if we will manage

**Comment by anabsolutesloth** [comment]
will fix boss jsons and update ftd when not lazy, issue will be resolve when such happens

**Comment by anabsolutesloth** [comment]
fixed as of MCE 1.6, as FTD is goned.
expect ZenSummoning in the 1.7 Space Overhaul if it ever comes out.
