### ISSUE TITLE
[BUG] Describe the bug in a single sentence

### ISSUE THREAD

**Issue by Hether562** [Minecraft-Eternal/MC-Eternal-1.12#320]
**Describe the bug**

I cannot claim any chunks in any dimensions other than the overworld. It simply won't let me, i got the sound like i'm clicking but nothing happens

**Version of MC Eternal**
Which version of the mod pack are you on? 1.4.4

**Comment by anabsolutesloth** [comment]
This is intentional, to a degree, but is also being removed next update, as it's a bit silly.
It's also not "all" dimensions, but a few select ones that most would try to claim chunks in
If you want to remove it yourself right now, go to `ftbutilities.cfg` and make the following option:
```    # Dimensions where chunk claiming isn't allowed.
    I:blocked_claiming_dimensions <
        10
        1000
        8
        -1
        1
     >
```
look like this
```    # Dimensions where chunk claiming isn't allowed.
    I:blocked_claiming_dimensions <
     >
```
