### ISSUE TITLE
[SUGGESTION] Disable the Lead Pet

### ISSUE THREAD

**Issue by IcewaveGaming** [Minecraft-Eternal/MC-Eternal-1.12#492]
### Description of Suggestion

Disables the lead pet.

### How does this improve the experience?

Lead Pet can leash almost any mob, with the only restriction being the ender dragon. This effectively disables their AI. And since the lead pet is obtainable very early on, this nullifies the danger of any mob in the game, bosses included, because you can simply leash them before beating them to death. The pet also has no limit to how many mobs it can leash at once.

### Screenshots

![image](https://user-images.githubusercontent.com/88635231/201722443-90e8f323-4ee4-4280-9101-bd656191f64e.png)
![image](https://user-images.githubusercontent.com/88635231/201722517-239d3b2e-4dd7-46d2-9dd1-d4ea4c49609b.png)
![image](https://user-images.githubusercontent.com/88635231/201722614-fb831c03-1ddb-499b-ae4b-1d017797740e.png)
![image](https://user-images.githubusercontent.com/88635231/201722744-0b417696-dd17-4aa0-b01a-2a2d229438a2.png)
![image](https://user-images.githubusercontent.com/88635231/201723093-03c35f1a-ff7e-41df-9f3e-a3e1869eb1d7.png)
![image](https://user-images.githubusercontent.com/88635231/201723216-3ee879a0-67c9-4deb-80a4-a4e245dc0917.png)
![image](https://user-images.githubusercontent.com/88635231/201724468-1af902a5-c372-4093-a1f9-50e813601595.png)

**Comment by IcewaveGaming** [comment]
EDIT: There is _one_ restriction on the lead pet, and it's the only one as far as I can tell - it can't leash the ender dragon.

**Comment by 8q16d** [comment]
Can you disable the Slime Pet too while you're at it? It also makes you completely invincible as long as you have golden apples, which are really easy to get a lot of. It doesn't make sense why the Juggernaut Pet and Last Stand are disabled, but the Slime Pet isn't, even though it is arguably better than both of those. The Slime Pet is also super easy to obtain, since you can craft a Petrifier with a Wither Pet (costs 1 nether star) and right click on a slime. Also, make sure to remove the pets from the Inventory Pet Master quest.

**Comment by anabsolutesloth** [comment]
fixed as of 1.6.1, both lead and slime pets are now disabled
