### ISSUE TITLE
Migration from Eternal MC Lite

### ISSUE THREAD

**Issue by DuanYuFi** [Minecraft-Eternal/MC-Eternal-1.12#500]
Hi,
I have an multiplayer server running with Eternal MC Lite 1.3.8.1, and now I want to "update" the modpack (or to be precisely, I want to migrate the saves to Eternal MC). So is there any way to do so？That includes keep all the worlds, items and better to keep the stuffs in FTB quests.
Thanks, looking forward to get reply!

**Comment by anabsolutesloth** [comment]
while you can technically migrate from MCE lite to full, it will have severe consequences on your world and is not recommended, we can't really give any support because of how drastic the difference is currently.

MCE lite may get a reboot by forking off of the current release in the future, instead of trying to update it to match full MCE, but as of now, it's pretty much dead.
