### ISSUE TITLE
[BUG] Can't open the game

### ISSUE THREAD

**Issue by Zelkieee** [Minecraft-Eternal/MC-Eternal-1.12#529]
### Description of the Bug

I got it over CurseForge. When I download it, it loads as it should, but when it's done, it crashes right away. It says that it is "unknown" that is the problem.. I have tried to repair it over CurseForge, I have 1000GB free space and I have no other mods on my PC. So I really don't know what else to do.. 

### Expected Behaviour

I just expected it to open up so I could choose between singleplayer and multiplayer.

### Modpack Version

1.6.1

**Comment by anabsolutesloth** [comment]
This report lacks sufficient information to solve the issue, and crash issues such as this are preferred to be handled on our discord, we can generally provide a much faster response there.
i will leave this open, but if no response is given, this will be closed.
if you come to our discord, please let us know that you made this issue on the github, so that i can be closed afterwards.
