### ISSUE TITLE
[BUG] *Can't place blocks*

### ISSUE THREAD

**Issue by PotatoCreator** [Minecraft-Eternal/MC-Eternal-1.12#558]
### Description of the Bug

When I got into my inventory and put some block into hotbar, leave the inventory. When I try to place a block, immediately it dissapears. It also dissapears from my hotbar. If I press the inventory sorting button, the blocks appear back, but still does in same loop. 

Solution I found, If you hold the item on mouse and click with it on baubles icon. then the bug fixes for sometime.

### Expected Behaviour

When I place a block, I expect it to be placed.

### Modpack Version

1.6.2.2

### Screenshots

https://streamable.com/gko5ob

### Log

Not sure

### Extra Info

Fresh download, no changes

**Comment by anabsolutesloth** [comment]
This sounds like a fairly common issue known as an Inventory Desync.
they're caused by a number of things, but one common and consistent cause cause is the Spell Library keybind from Roots, pressing it while not holding a staff tends to initiate one.
The effects are pretty simple, any changes to your regular main inventory from the standard Inventory menu won't be communicated to the serverside.
you can cure it by changing dimensions or logging in and out of the world.

full-on fixing it is not reasonable, it's a problem within Forge.

**Comment by PotatoCreator** [comment]
Why was this closed?

**Comment by anabsolutesloth** [comment]
i explained the problem, figured it got everything that needed to be gotten across, and as noted before, a permanent fix in the pack is unreasonable.

**Comment by PotatoCreator** [comment]
> i explained the problem, figured it got everything that needed to be gotten across, and as noted before, a permanent fix in the pack is unreasonable.

Oh, im sorry, I don't know how I missed your reply. Must be that email just said that it was closed, but didnt show your message.
